export const BAZAR_ITEM_SUGGESTIONS = [
  "Ada",
  "Akhrot",
  "Amra",
  "Anaros",
  "Apple",
  "Arhar Dal",
  "Ata",
  "Atop Chal",
  "Bagda Chingri",
  "Baked Beans",
  "Bangi",
  "Barley",
  "Basmati Chal",
  "Bata Mach",
  "Beans",
  "Begun",
  "Beson",
  "Beet",
  "Biscuit",
  "Bit Lobon",
  "Blueberry",
  "Boal",
  "Borboti",
  "Boroi",
  "Broccoli",
  "Brown Rice",
  "Broiler Murgi",
  "Bun",
  "Buter Dal",
  "Butter",
  "Cake",
  "Candy",
  "Capsicum",
  "Carrot",
  "Chal",
  "Chal Kumra",
  "Chanachur",
  "Chat Moshla",
  "Chatni",
  "Cheese",
  "Chia Seed",
  "Chicken",
  "Chili Sauce",
  "Chingri",
  "Chingri Mach",
  "Chingri Shutki",
  "Chini",
  "Chips",
  "Chira",
  "Chocolate",
  "Chitol",
  "Chola",
  "Chola Dal",
  "Cocoa Powder",
  "Coffee",
  "Condensed Milk",
  "Corn Flour",
  "Cornflakes",
  "Coral Mach",
  "Cracker",
  "Cream",
  "Curry Pata",
  "Custard Powder",
  "Dab",
  "Daber Pani",
  "Dalim",
  "Daruchini",
  "Data Shak",
  "Deshi Murgi",
  "Dherosh",
  "Dhonia",
  "Dhonia Gura",
  "Dhonia Pata",
  "Dim",
  "Doi",
  "Dry Fruits",
  "Elach",
  "Fish Sauce",
  "Flour",
  "Food Color",
  "French Fries",
  "Frozen Chicken",
  "Frozen Mach",
  "Frozen Sobji",
  "Fulkopi",
  "Garom Moshla",
  "Gajor",
  "Ghee",
  "Golda Chingri",
  "Golmorich",
  "Gom",
  "Gorur Mangsho",
  "Green Tea",
  "Gur",
  "Hash",
  "Hasher Dim",
  "Holud Gura",
  "Hot Chocolate",
  "Ice Cream",
  "Ilish",
  "Jam",
  "Jelly",
  "Jhinga",
  "Jira",
  "Jira Gura",
  "Jolpai",
  "Joyfol",
  "Joytri",
  "Juice",
  "Kacha Kola",
  "Kacha Morich",
  "Kajubadam",
  "Kalojira",
  "Kamranga",
  "Kasundi",
  "Katla",
  "Kathal",
  "Kathbadam",
  "Ketchup",
  "Khejur",
  "Khesari Dal",
  "Kiwi",
  "Kochu",
  "Kochur Loti",
  "Koi",
  "Kolmi Shak",
  "Kola",
  "Korola",
  "Kumra Seed",
  "Kumra Shak",
  "Lachcha Semai",
  "Lal Capsicum",
  "Lal Chal",
  "Lal Shak",
  "Lau",
  "Lau Shak",
  "Lebu",
  "Lichu",
  "Liquid Milk",
  "Lobon",
  "Lobongo",
  "Macaroni",
  "Magur",
  "Malta",
  "Mashkalai Dal",
  "Mayonnaise",
  "Methi",
  "Mineral Water",
  "Miniket Chal",
  "Mixed Dal",
  "Modhu",
  "Mocha",
  "Morich Gura",
  "Mosur Dal",
  "Mouri",
  "Mrigel",
  "Mug Dal",
  "Mula",
  "Murgi",
  "Murgir Dim",
  "Muri",
  "Mushroom",
  "Misti Alu",
  "Misti Doi",
  "Misti Kumra",
  "Moyda",
  "Narikel",
  "Narikel Dudh",
  "Narikel Tel",
  "Nashpati",
  "Noodles",
  "Nuggets",
  "Oats",
  "Olive Oil",
  "Orange",
  "Oregano",
  "Oyster Mushroom",
  "Oyster Sauce",
  "Pabda",
  "Palong Shak",
  "Pangash",
  "Papaya",
  "Parsley",
  "Pasta",
  "Pauruti",
  "Payaj",
  "Pepe",
  "Pepper",
  "Pesta",
  "Peyara",
  "Pizza Base",
  "Ponir",
  "Popcorn",
  "Posto",
  "Potol",
  "Powder Milk",
  "Pudina Pata",
  "Pui Shak",
  "Puti Mach",
  "Quail",
  "Quail Dim",
  "Rice Bran Oil",
  "Rosemary",
  "Rosun",
  "Rui",
  "Sabudana",
  "Sagu",
  "Sausage",
  "Semai",
  "Shing",
  "Shim",
  "Shosha",
  "Shukna Morich",
  "Shutki",
  "Soft Drink",
  "Sofeda",
  "Sorisha",
  "Sorisha Shak",
  "Sorishar Tel",
  "Soup",
  "Soyabin Tel",
  "Strawberry",
  "Suji",
  "Sunflower Oil",
  "Sunflower Seed",
  "Sweet Corn",
  "Tejpata",
  "Tel",
  "Tengra",
  "Thyme",
  "Til",
  "Tilapia",
  "Tishi",
  "Toast",
  "Tok Doi",
  "Tomato",
  "Tomato Paste",
  "Tomato Sauce",
  "Tormuj",
  "Tulsi",
  "Tuna",
  "Turkey",
  "Vanilla Essence",
  "Veli Gur",
  "Vinegar",
  "Yeast",
] as const;

function getActiveSegment(value: string): string {
  const lastComma = value.lastIndexOf(",");
  const segment = lastComma >= 0 ? value.slice(lastComma + 1) : value;
  return segment.trimStart();
}

export function applyBazarSuggestion(value: string, suggestion: string): string {
  const lastComma = value.lastIndexOf(",");
  if (lastComma >= 0) {
    const prefix = value.slice(0, lastComma + 1);
    return `${prefix} ${suggestion}`;
  }
  return suggestion;
}

export function filterBazarSuggestions(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const startsWith: string[] = [];
  const includes: string[] = [];

  for (const item of BAZAR_ITEM_SUGGESTIONS) {
    const lower = item.toLowerCase();
    if (lower.startsWith(q)) {
      startsWith.push(item);
    } else if (lower.includes(q)) {
      includes.push(item);
    }
  }

  return [...startsWith, ...includes].slice(0, limit);
}

export function getBazarSuggestionQuery(value: string): string {
  return getActiveSegment(value);
}
